Traceback (most recent call last):
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
countries = df.loc[df["life_expectancy_t"] > 80, "country"].unique()

# use the DataFrame unique() method to remove duplicated countries
countries.unique() 
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [12], line 4[0m
[1;32m      1[0m countries [38;5;241m=[39m df[38;5;241m.[39mloc[df[[38;5;124m"[39m[38;5;124mlife_expectancy_t[39m[38;5;124m"[39m] [38;5;241m>[39m [38;5;241m80[39m, [38;5;124m"[39m[38;5;124mcountry[39m[38;5;124m"[39m][38;5;241m.[39munique()
[1;32m      3[0m [38;5;66;03m# use the DataFrame unique() method to remove duplicated countries[39;00m
[0;32m----> 4[0m countries[38;5;241m.[39munique()

[0;31mAttributeError[0m: 'numpy.ndarray' object has no attribute 'unique'
AttributeError: 'numpy.ndarray' object has no attribute 'unique'

