Traceback (most recent call last):
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
y = np.array(2,1,2,3,2,4)
y_hat = np.array(1,1,1,2,2,1)

mse = (1/6) * np.sum(np.square(y-y_hat))
print(mse)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [12], line 1[0m
[0;32m----> 1[0m y [38;5;241m=[39m np[38;5;241m.[39marray([38;5;241m2[39m,[38;5;241m1[39m,[38;5;241m2[39m,[38;5;241m3[39m,[38;5;241m2[39m,[38;5;241m4[39m)
[1;32m      2[0m y_hat [38;5;241m=[39m np[38;5;241m.[39marray([38;5;241m1[39m,[38;5;241m1[39m,[38;5;241m1[39m,[38;5;241m2[39m,[38;5;241m2[39m,[38;5;241m1[39m)
[1;32m      4[0m mse [38;5;241m=[39m ([38;5;241m1[39m[38;5;241m/[39m[38;5;241m6[39m) [38;5;241m*[39m np[38;5;241m.[39msum(np[38;5;241m.[39msquare(y[38;5;241m-[39my_hat))

[0;31mTypeError[0m: array() takes from 1 to 2 positional arguments but 6 were given
TypeError: array() takes from 1 to 2 positional arguments but 6 were given

