Traceback (most recent call last):
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexiacardona/.conda/envs/MCBPractical2/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df2 = pd.read_csv("data/world-bank-1_data.txt")
df.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mParserError[0m                               Traceback (most recent call last)
Cell [0;32mIn [13], line 1[0m
[0;32m----> 1[0m df2 [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m"[39m[38;5;124mdata/world-bank-1_data.txt[39m[38;5;124m"[39m)
[1;32m      2[0m df[38;5;241m.[39mhead()

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/util/_decorators.py:311[0m, in [0;36mdeprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper[0;34m(*args, **kwargs)[0m
[1;32m    305[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(args) [38;5;241m>[39m num_allow_args:
[1;32m    306[0m     warnings[38;5;241m.[39mwarn(
[1;32m    307[0m         msg[38;5;241m.[39mformat(arguments[38;5;241m=[39marguments),
[1;32m    308[0m         [38;5;167;01mFutureWarning[39;00m,
[1;32m    309[0m         stacklevel[38;5;241m=[39mstacklevel,
[1;32m    310[0m     )
[0;32m--> 311[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/io/parsers/readers.py:680[0m, in [0;36mread_csv[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[1;32m    665[0m kwds_defaults [38;5;241m=[39m _refine_defaults_read(
[1;32m    666[0m     dialect,
[1;32m    667[0m     delimiter,
[0;32m   (...)[0m
[1;32m    676[0m     defaults[38;5;241m=[39m{[38;5;124m"[39m[38;5;124mdelimiter[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m,[39m[38;5;124m"[39m},
[1;32m    677[0m )
[1;32m    678[0m kwds[38;5;241m.[39mupdate(kwds_defaults)
[0;32m--> 680[0m [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/io/parsers/readers.py:581[0m, in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    578[0m     [38;5;28;01mreturn[39;00m parser
[1;32m    580[0m [38;5;28;01mwith[39;00m parser:
[0;32m--> 581[0m     [38;5;28;01mreturn[39;00m [43mparser[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1254[0m, in [0;36mTextFileReader.read[0;34m(self, nrows)[0m
[1;32m   1252[0m nrows [38;5;241m=[39m validate_integer([38;5;124m"[39m[38;5;124mnrows[39m[38;5;124m"[39m, nrows)
[1;32m   1253[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1254[0m     index, columns, col_dict [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m
[1;32m   1255[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[1;32m   1256[0m     [38;5;28mself[39m[38;5;241m.[39mclose()

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:225[0m, in [0;36mCParserWrapper.read[0;34m(self, nrows)[0m
[1;32m    223[0m [38;5;28;01mtry[39;00m:
[1;32m    224[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mlow_memory:
[0;32m--> 225[0m         chunks [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_reader[49m[38;5;241;43m.[39;49m[43mread_low_memory[49m[43m([49m[43mnrows[49m[43m)[49m
[1;32m    226[0m         [38;5;66;03m# destructive to chunks[39;00m
[1;32m    227[0m         data [38;5;241m=[39m _concatenate_chunks(chunks)

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:805[0m, in [0;36mpandas._libs.parsers.TextReader.read_low_memory[0;34m()[0m

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:861[0m, in [0;36mpandas._libs.parsers.TextReader._read_rows[0;34m()[0m

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:847[0m, in [0;36mpandas._libs.parsers.TextReader._tokenize_rows[0;34m()[0m

File [0;32m~/.conda/envs/MCBPractical2/lib/python3.10/site-packages/pandas/_libs/parsers.pyx:1960[0m, in [0;36mpandas._libs.parsers.raise_parser_error[0;34m()[0m

[0;31mParserError[0m: Error tokenizing data. C error: Expected 1 fields in line 184, saw 2

ParserError: Error tokenizing data. C error: Expected 1 fields in line 184, saw 2


